submdspan: static slices
kokkos/mdspan pull request #159
Opened 2022-07-15 17:05 UTC by mhoemmen

When `submdspan` is given a `tuple<integral_constant<size_t, Value0>, integral_constant<size_t, Value1>>` as a slice specifier, preserve the compile-time values in the returned `mdspan`'s `extents_type`.

2022-07-26 03:38 UTC, crtrott requested changes
Can you add a test for 3D with the static slice happening in the middle, feels like first and last might be special, otherwise looks good.

2022-07-27 22:15 UTC, mhoemmen commented
@crtrott wrote:
> Can you add a test for 3D with the static slice happening in the middle, feels like first and last might be special, otherwise looks good.

Thanks Christian! : - )  I added more 3-D tests, including

* (tuple, full, tuple),
* (full, tuple, full),
* (full, full, index), and
* (full, index, full).

I also increased the variety of layouts exercised, and added 1-D tests.

2022-07-28 15:40 UTC, crtrott approved these changes

2022-07-28 15:52 UTC, nliber approved these changes

2022-07-28 16:13 UTC, merged