#270: missing qualifiers in compressed_pair
kokkos/mdspan pull request #271
Opened 2023-05-25 19:04 UTC by nmm0

Closes #270

Also, I switched away from the `_MDSPAN_TRAITS` macro in this usage since we are dropping C++14 support anyway

2023-05-25 19:19 UTC, crtrott approved these changes

2023-05-25 19:19 UTC, crtrott requested changes
Lets catch the C++14 not supported in make

2023-05-25 21:14 UTC, nmm0 commented
> Lets catch the C++14 not supported in make

Pushed these changes

2023-05-25 21:35 UTC, dalg24 requested changes
Why do we do the C++14 in the same PR?
That does not seem like a good idea
What prevents you to just qualify `_MDSPAN_TRAIT(std::is_empty, _T)` or whatnot

2023-05-25 22:09 UTC, nmm0 commented
I made the PR C++14 compatible

2023-05-25 22:10 UTC, dalg24 approved these changes

2023-05-25 22:11 UTC, dalg24 commented
Make sure you update the title line and description

2023-06-06 22:53 UTC, crtrott approved these changes

2023-06-06 22:53 UTC, merged